// Regras de Produção - Don Corleone
package OEIP

import OEIP.*;
import robocode.*;
import robocode.ScannedRobotEvent;

query "consult actions"
	action: DonCorleoneAction()
end

declare:
	previousEnergy: double
end

declare:
	movementDirection: int
end

declare:
	gunDirection: int
end

declare:
	direction: static double
end

declare:
	movingForward: boolean
end

declare Enemy:
	name: String
	enemyX: double
	enemyY: double
	distante: double
	energy: double
	velocity: double
	heading: double
	headingRadians: double
end

rule "debug actions of the same type"
when
	$action1: DonCorleoneAction($type: type, $priority1: priority)
	$action2: DonCorleoneAction(type == $type, $priority2: priority)
	eval ($priority1 > $priority2)
then
	retract($action2);
	System.out.println("rule 1");
end

rule "detect robot -> send infos"
when
	(exists onScannedRobot())
	$scannedOpponent: ScannedRobotEvent()
	not (isTeammate($scannedOpponent.getName()))
then
	broadcastMessage(new Info($scannedOpponent.getDistance(),
									$scannedOpponent.getEnergy(),
									enemyX,
									enemyY,
									getHeading(),
									getVelocity(),
									getHeadingRadians()))
	setTurnRight($scannedOpponent.getBearing() + 90 - 30 * movementDirection)
end

rule "hit shot -> change direction"
when
	(exists onHitByBullet(HitBulletEvent e))
then
	$movementDirection = -movementDirection
end

rule "collide wall -> turn"
when
	(exists onHitWall(HitWallEvent e))
then
	turnRight(angle - 100)
end

rule "collide robot -> shoot"
when
	$movementDirection = -movementDirection
	(exists onHitRobot(HitRobotEvent e))
	not (isTeammate(name))
then
	insert(new DonCorleoneAction(Action.TURN_CANNON_RIGHT, 2, 1))
end